// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oboyihxjjswknvbvluwe.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9ib3lpaHhqanN3a252YnZsdXdlIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM0Mjg1NzgsImV4cCI6MjA1OTAwNDU3OH0.f0EhqAbE8_HohJZqjhE4j_pR3N9gKo0mnsVFn9v7T4A";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);